#!/bin/sh -x

javac src/com/satou/somath/serveur/*.java
javac src/com/satou/somath/client/*.java

gnome-terminal --geometry 103x25+37+52 -x 	java src.com.satou.somath.serveur.PacmanServeur
gnome-terminal --geometry 103x25+978+52 -x 	java src.com.satou.somath.client.PacmanClient 
gnome-terminal --geometry 103x25+978+550 -x 	java src.com.satou.somath.client.PacmanClient 
#gnome-terminal --geometry 103x29+37+580 -x 	java client/PacmanClient 
#gnome-terminal --geometry 103x29+978+580 -x 	java client/PacmanClient 

